<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EmployeeProfiles', 'doctrine');

/**
 * BaseEmployeeProfiles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $profile_id
 * @property string $profile_code
 * @property string $description
 * @property Doctrine_Collection $Employee
 * 
 * @method integer             getProfileId()    Returns the current record's "profile_id" value
 * @method string              getProfileCode()  Returns the current record's "profile_code" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method Doctrine_Collection getEmployee()     Returns the current record's "Employee" collection
 * @method EmployeeProfiles    setProfileId()    Sets the current record's "profile_id" value
 * @method EmployeeProfiles    setProfileCode()  Sets the current record's "profile_code" value
 * @method EmployeeProfiles    setDescription()  Sets the current record's "description" value
 * @method EmployeeProfiles    setEmployee()     Sets the current record's "Employee" collection
 * 
 * @package    uss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEmployeeProfiles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('employee_profiles');
        $this->hasColumn('profile_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('profile_code', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '30',
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Employee', array(
             'local' => 'profile_id',
             'foreign' => 'emp_profile_id'));
    }
}