# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css, ../jslib/jquery/themes/base/jquery.ui.all.css]

  javascripts:    [../jslib/jquery/jquery-1.4.2.js, ../jslib/jquery/ui/jquery.ui.core.js, ../jslib/jquery/ui/jquery.ui.widget.js, ../jslib/jquery/ui/jquery.ui.datepicker.js, dateTimePicker.js]

  has_layout:     true
  layout:         layout
