Areas:
  connection: doctrine
  tableName: areas
  columns:
    area_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    area_code:
      type: string(5)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    area_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    zone_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Zones:
      local: zone_id
      foreign: zone_id
      type: one
    Customer:
      local: area_id
      foreign: area_id
      type: many
    Employee:
      local: area_id
      foreign: area_id
      type: many
Category:
  connection: doctrine
  tableName: category
  columns:
    category_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    category_name:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Employee:
      local: category_id
      foreign: category_id
      type: many
    Items:
      local: category_id
      foreign: category_id
      type: many
Complaints:
  connection: doctrine
  tableName: complaints
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    complaint_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    complaint_code:
      type: string(40)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    customer_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    assigned_emp_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    item_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    closed_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Customer:
      local: customer_id
      foreign: customer_id
      type: one
    Employee:
      local: assigned_emp_id
      foreign: emp_id
      type: one
    Items:
      local: item_id
      foreign: item_id
      type: one
CustRegItems:
  connection: doctrine
  tableName: cust_reg_items
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    customer_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    item_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Customer:
      local: customer_id
      foreign: customer_id
      type: one
    Items:
      local: item_id
      foreign: item_id
      type: one
Customer:
  connection: doctrine
  tableName: customer
  columns:
    customer_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    reg_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    person_code:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sur_name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mobile:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    zone_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    area_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    reg_expiry:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    address:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Zones:
      local: zone_id
      foreign: zone_id
      type: one
    Areas:
      local: area_id
      foreign: area_id
      type: one
    Complaints:
      local: customer_id
      foreign: customer_id
      type: many
    CustRegItems:
      local: customer_id
      foreign: customer_id
      type: many
Employee:
  connection: doctrine
  tableName: employee
  columns:
    emp_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    reg_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    emp_code:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sur_name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mobile:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    zone_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    area_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    role:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    working_under:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    skill_set:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    category_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    address:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Employee:
      local: emp_id
      foreign: working_under
      type: many
    Zones:
      local: zone_id
      foreign: zone_id
      type: one
    Areas:
      local: area_id
      foreign: area_id
      type: one
    Category:
      local: category_id
      foreign: category_id
      type: one
    Complaints:
      local: emp_id
      foreign: assigned_emp_id
      type: many
Items:
  connection: doctrine
  tableName: items
  columns:
    item_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    item_name:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    item_price:
      type: float(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    category_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    item_description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Category:
      local: category_id
      foreign: category_id
      type: one
    Complaints:
      local: item_id
      foreign: item_id
      type: many
    CustRegItems:
      local: item_id
      foreign: item_id
      type: many
Zones:
  connection: doctrine
  tableName: zones
  columns:
    zone_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    zone_code:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    zone_name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Areas:
      local: zone_id
      foreign: zone_id
      type: many
    Customer:
      local: zone_id
      foreign: zone_id
      type: many
    Employee:
      local: zone_id
      foreign: zone_id
      type: many
